feat: Add birch branch to dev config
mozilla-releng/shipit pull request #1316
Opened 2023-05-03 21:03 UTC by hneiva

2023-05-03 21:12 UTC, bhearsum requested changes
I'd suggest you add this to `development` as well just to be safe. Or you can try this one, and then switch to that one if needed.

2023-05-03 21:12 UTC, bhearsum commented on frontend/src/configs/dev.js
> +          prettyName: 'Try',
These three strings should be talking about birch - not try.

2023-05-03 21:12 UTC, bhearsum commented on frontend/src/configs/dev.js
> +          prettyName: 'Try',
It also looks like the branch should be `projects/birch` based on how I see Beta configure in production: https://github.com/mozilla-releng/shipit/blob/172d396f61bb9873b9ebc1ab2214a54d6b8c07f0/frontend/src/configs/production.js#L19. (It seems that we need the path part of the url here.)

2023-05-03 22:55 UTC, bhearsum approved these changes

2023-05-04 07:38 UTC, jcristau reviewed
Can you explain why we need/want this?

2023-05-04 11:58 UTC, bhearsum commented
> Can you explain why we need/want this?

I recommended that we do this in order to make it possible to test partner & eme-free notarization tasks. (Something we can't do on Try AFAIK.)

2023-05-04 14:24 UTC, jcristau commented
We can't test notarization on try but we don't need shipit either, we can trigger release-promotion graphs from th or tc directly?

2023-05-04 14:40 UTC, bhearsum commented
> We can't test notarization on try but we don't need shipit either, we can trigger release-promotion graphs from th or tc directly?

It's not strictly necessary, yeah, but it's a bit more convenient? I could be convinced not to bother with this...

2023-05-08 17:27 UTC, gbrownmozilla approved these changes

2023-05-09 13:50 UTC, jcristau requested changes
One thing is I'm a bit worried about mixing a level3 repo with staging infrastructure.

Relatedly, and probably more importantly, the project/releng/shipit/staging tc client only has scopes to trigger level1 hooks.

2023-05-09 14:12 UTC, bhearsum commented
In any case - I think we _really_ ought to have a way to test notarization changes outside of landing them to central - at least in the short term while this is under active development.

2023-05-09 14:18 UTC, bhearsum commented
@jcristau and I chatted about this elsewhere. I got a bit mixed up in my previous comment - we can still test release promotion without this by kicking it off directly with hooks instead of Ship It (and it looks like we'll have to due to ship it scopes).

2023-05-09 20:33 UTC, hneiva commented
Sounds like it's safe to close this for now, as it's not needed.

2023-05-09 20:33 UTC, closed without merging