Update current and next ESR versions
mozilla-releng/shipit pull request #1358
Opened 2023-08-28 20:57 UTC by ahal

I missed this in the regular product details update as most cycles we don't decomission an ESR.

2023-08-29 07:31 UTC, jcristau requested changes
This should only land in 4 weeks, AFAIK.

2023-08-29 13:04 UTC, ahal commented
@jcristau Ah ok, thanks for catching! Do you know why that is?

2023-09-25 22:43 UTC, gbrownmozilla approved these changes

2023-09-26 09:06 UTC, jcristau approved these changes
Should land/deploy today after the 115.3.0 release.

2023-09-26 12:59 UTC, merged