Fix for Issue #1355
mozilla-releng/shipit pull request #1360
Opened 2023-09-18 14:30 UTC by salmanzego

Fixed Issue of Redirection to the pending releases page when a new release is submitted

2023-09-25 23:30 UTC, gabrielBusta commented on frontend/src/views/NewRelease/index.jsx
> +                if (response === 201) {
```suggestion
                if (!response.error) {
```

2023-09-25 23:31 UTC, gabrielBusta requested changes

2023-09-25 23:31 UTC, gabrielBusta commented on frontend/src/views/NewRelease/index.jsx
> +                if (response === 201) {
The action returns the response data, not the response itself.

2023-11-20 19:08 UTC, salmanzego commented on frontend/src/views/NewRelease/index.jsx
> +                if (response === 201) {
Oh sorry, I hadn't thought about it. Changed it. Thank you.

2023-12-26 14:21 UTC, salmanzego commented
Hai, Can you please review this @gabrielBusta

2024-01-24 03:04 UTC, closed without merging