fix: redirect to the pending releases page after submitting a release
mozilla-releng/shipit pull request #1387
Opened 2024-01-10 18:36 UTC by gabrielBusta

fixes #1355

2024-01-10 18:40 UTC, gabrielBusta commented
Should I be passing in the "group" somewhere when redirecting back to the releases page?

2024-01-10 20:53 UTC, ahal commented
> Should I be passing in the "group" somewhere when redirecting back to the releases page?

Yeah, it should be a url parameter, e.g: `/?group=security`. It'll default to "firefox" if unspecified, so no need to pass it if `group == "firefox"` (but it doesn't hurt to pass it either.

2024-01-10 20:54 UTC, ahal requested changes
Requesting changes for the 'group' issue

2024-02-07 15:42 UTC, ahal approved these changes

2024-02-07 15:42 UTC, bhearsum approved these changes

2024-02-07 15:43 UTC, merged