RELENG-302 - s/email/ldap group/ for shipit scopes
mozilla-releng/shipit pull request #782
Opened 2021-06-11 19:28 UTC by jmaher

2021-06-11 20:04 UTC, escapewindow commented
> RELENG-302 - s/email/ldap group/ for shipit scopes

Should we rename this `RELENG-487 - ...` ?

2021-06-11 20:56 UTC, escapewindow requested changes
I think this looks good, logic-wise, thank you!
a) have we tested locally and/or on shipit-stage? and
b) some of the variable names aren't as clear as they could be. I mentioned some potential replacements.

2021-06-11 20:56 UTC, escapewindow commented on api/src/backend_common/auth.py
> +    def get_id(self):
`get_ldap_groups` or similar may be a better name here.

2021-06-11 20:56 UTC, escapewindow commented on api/src/backend_common/auth.py
> +        users_ldap = self.get_id()
maybe `user_groups` or `user_ldap_groups` ?

2021-06-11 20:56 UTC, escapewindow commented on api/src/backend_common/auth.py
> +        return [permission for permission, users in all_permissions.items() if set(users_ldap).intersection(set(users))]
`users` is probably a misnomer here -- we will have a mapping of `scope` to `ldap groups`. Maybe `permission_groups`?

2021-06-14 22:18 UTC, jmaher commented
I tested this locally via a local shipit instance. If this looks good, I can do it on shipit staging and get more traction there.

2021-06-14 23:32 UTC, escapewindow reviewed
Overall looks good! I'd like to see the shipit stage results :)

2021-06-14 23:32 UTC, escapewindow commented on api/src/backend_common/auth.py
> +        return isinstance(other, BaseUser) and self.get_ldap_groups() == other.get_ldap_groups()
Hm, I would have thought the email might have been a better comparison?

I'm curious if we have any non-Auth0 users that use shipit; if so, some of these classes may be obsolete.

2021-06-14 23:32 UTC, escapewindow commented on api/src/shipit_api/admin/api.py
> +    users_ldap = current_user.get_id()
Hm, might be a `get_ldap_groups` ?

2021-06-15 17:54 UTC, escapewindow commented
@bhearsum You may have some opinions about this refactor; let us know if you do?

2021-06-15 18:17 UTC, bhearsum commented on api/src/backend_common/auth.py
> +    def get_ldap_groups(self):
Is there a way we can rework this so that `TaskclusterUser` is returning a sensible value here? If `get_ldap_groups` isn't a thing that makes sense in the context of a `TaskclusterUser`, it doesn't belong as part of the `BaseUser` set of methods IMO.

2021-06-15 18:17 UTC, bhearsum commented on api/src/backend_common/auth.py
> +    def get_email(self):
Is this really an e-mail for a `TaskclusterUser`?

2021-06-15 18:17 UTC, bhearsum commented on api/src/shipit_api/admin/settings.py
> +XPI_MOZILLAONLINE_PRIVILEGED_ADMIN_GROUP = ["xpi_mozillaonline_admin"]
This is so much cleaner!

A consistency nit though: in the code above, you use `ldap_groups` a lot, but here you're just using `GROUP`. We should be consistent and either always call them "ldap groups" or never.

2021-06-15 23:25 UTC, escapewindow reviewed
I think I just have some concerns about the logic around the areas I commented. Overall this is a good cleanup, thank you!

2021-06-15 23:25 UTC, escapewindow commented on api/src/backend_common/auth.py
> -class TaskclusterUser(BaseUser):
That's one way to do it :)
I don't foresee us moving back to tc auth, so this probably works.

2021-06-15 23:25 UTC, escapewindow commented on api/src/backend_common/auth.py
> +def parse_header(request):
Hm, I think this changes the `parse_header` behavior from returning `None` if you're not authorized, to returning the `NO_AUTH` object. Let's do a little testing around this?

2021-06-15 23:25 UTC, escapewindow commented on api/src/shipit_api/admin/xpi.py
> +    if users_ldap in [s.completed_by for s in phase_obj.signoffs]:
Hm, we may be saving the email in the signoffs, not the ldap groups, no?

2021-06-15 23:25 UTC, escapewindow commented on api/src/shipit_api/admin/api.py
> +    if users_ldap in [s.completed_by for s in phase_obj.signoffs]:
Same here, I think we're using the email in the signoffs list, not the ldap group?

2021-06-15 23:25 UTC, escapewindow commented on api/src/shipit_api/admin/api.py
> +    if product_disabled:
Hm, if taskcluster auth types weren't used, this block may be obsolete.

2021-06-15 23:28 UTC, escapewindow commented on api/src/backend_common/auth.py
> +def parse_header(request):
Per https://flask-login.readthedocs.io/en/latest/_modules/flask_login/login_manager.html , 

```
The function you set should take an authentication token and
return a user object, or `None` if the user does not exist.
```

2021-06-21 20:28 UTC, jmaher commented on api/src/shipit_api/admin/api.py
> +    if users_ldap in [s.completed_by for s in phase_obj.signoffs]:
good catch, I have cleaned this up and a few other areas where signoff id/email/completed_by/signoffs were not clearly using the email.

2021-06-21 20:29 UTC, jmaher commented on api/src/backend_common/auth.py
> +def parse_header(request):
yeah, fixing this to be None

2021-06-21 20:30 UTC, jmaher commented on api/src/shipit_api/admin/api.py
> +    if product_disabled:
this is the only thing I am not sure about, if a product is disabled, don't we want to skip this?

2021-06-21 23:00 UTC, escapewindow commented on api/src/shipit_api/admin/api.py
> +    if product_disabled:
I don't know what products are marked as disabled. The fact that this was under an `AuthType.TASKCLUSTER` if block tells me we're probably not using this, so it might be harmless.

2021-06-21 23:17 UTC, escapewindow approved these changes

2021-06-21 23:20 UTC, merged