Issue #439 - Notify additional people when releases change status
mozilla-releng/shipit pull request #809
Opened 2021-07-13 01:02 UTC by sarah-clements

I've tested this locally with my [xpi-manifest pr](https://github.com/mozilla-extensions/xpi-manifest/pull/120) pushed to staging-xpi-manifest and after creating an xpi release against staging-public, I saw emails (started and on completion) when a release was promoted to the next stage. However, since I was the scheduler and sign-off person for my tests, its an incomplete test so we'll want to do more of it on staging. 

Ben, it'd be good to have some tests for this. Where would you prefer I add them?

2021-07-13 01:12 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +    scheduled_phase = do_schedule_phase(session, phase_to_schedule, additional_shipit_emails)
I found it confusing that phase was re-declared in a few places (and even overwrite the phase arg), so I took the liberty of creating additional variables :)

2021-07-13 01:21 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +    # remove duplicates
It's occurred to me that I'm not sure if there is a check to remove duplicates in the staging-xpi-manifests pr, so I'll make a note to look into it.

2021-07-13 13:35 UTC, bhearsum requested changes
> Ben, it'd be good to have some tests for this. Where would you prefer I add them?

We've got tests for Ship It in https://github.com/mozilla-releng/shipit/tree/main/api/tests already - you can add them there.

2021-07-13 13:35 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +    if len(phases):
nit: `if phases` would be preferable here

2021-07-13 13:35 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +    additional_shipit_emails = []
I see you're converting this to a set later - you should just do that up here...

2021-07-13 13:35 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +            additional_shipit_emails = additional_shipit_emails + [signoff.completed_by for signoff in _phase.signoffs if signoff.completed_by is not None]
...and either use `set.add()` in a loop, or `set.update` to do this.

2021-07-13 13:35 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +    scheduled_phase = do_schedule_phase(session, phase_to_schedule, additional_shipit_emails)
...you could also update `do_schedule_phase` to support a set instead of requiring a list, or do the list conversion here. (It may already Just Work with a set, it's hard to tell by reading the code.)

2021-07-13 13:35 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +    scheduled_phase = do_schedule_phase(session, phase_to_schedule, additional_shipit_emails)
This is a good readability improvement, thanks!

2021-07-14 17:18 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +    if len(phases):
Why is it better? :)

2021-07-14 17:19 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +            additional_shipit_emails = additional_shipit_emails + [signoff.completed_by for signoff in _phase.signoffs if signoff.completed_by is not None]
Sure, I can start with a set but I still need to cast it to a list - empty or not - later on.

2021-07-14 17:27 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +    if len(phases):
Oh sorry - it's just a bit more pythonic IMO.

2021-07-14 17:28 UTC, bhearsum commented on api/src/shipit_api/admin/xpi.py
> +            additional_shipit_emails = additional_shipit_emails + [signoff.completed_by for signoff in _phase.signoffs if signoff.completed_by is not None]
Yeah, for sure. Starting with a set means you're never in a state where you can have duplicate entries though, which may help prevent bugs later.

2021-07-14 17:32 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +    scheduled_phase = do_schedule_phase(session, phase_to_schedule, additional_shipit_emails)
I think I'd prefer to keep the list conversion here.

2021-07-14 17:34 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +    if len(phases):
ok

2021-07-14 17:34 UTC, sarah-clements commented on api/src/shipit_api/admin/xpi.py
> +            additional_shipit_emails = additional_shipit_emails + [signoff.completed_by for signoff in _phase.signoffs if signoff.completed_by is not None]
Makes sense :)

2021-07-20 00:08 UTC, sarah-clements commented
@bhearsum I made changes based on feedback and added a unit test (held off on an integration test for now). Can you take another look please?

2021-07-20 13:56 UTC, bhearsum approved these changes
Looks good, thank you!

2021-07-20 17:48 UTC, merged